In [1]:
import tensorflow as tf
tf.__version__

'2.10.0'

In [2]:
#Create tensor with Constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#Check dimensions
scalar.ndim

0

In [6]:
#Create Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [8]:
#Check dimensions
vector.ndim

1

In [9]:
#Create Matrix
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
matrix.ndim

2